// This file is auto-generated by scripts/generate-gallery.js
// Do not edit this file manually. Run: node scripts/generate-gallery.js

export interface GalleryItem {
  type: "image" | "video";
  src: string;
  caption: string;
  category: "Photos" | "Videos";
}

export const galleryCategories = ["All", "Photos", "Videos"] as const;

export type GalleryCategory = typeof galleryCategories[number];

export const galleryItems: GalleryItem[] = [
  {
    "type": "image",
    "src": "/gallery/1.jpg",
    "caption": "Pranil Highlight - Photo 1",
    "category": "Photos"
  },
  {
    "type": "image",
    "src": "/gallery/2.jpg",
    "caption": "Pranil Highlight - Photo 2",
    "category": "Photos"
  },
  {
    "type": "image",
    "src": "/gallery/2ae0a1ba-fa82-41a8-bcb6-fa8352359d6d.jpg",
    "caption": "Pranil Moment - Photo 3",
    "category": "Photos"
  },
  {
    "type": "image",
    "src": "/gallery/7af16406-404b-4e79-8fc2-02b3091dd6ac.jpg",
    "caption": "Pranil Moment - Photo 4",
    "category": "Photos"
  },
  {
    "type": "image",
    "src": "/gallery/9c99e8b9-2216-4b62-99ef-c15aef8f7d42.jpg",
    "caption": "Pranil Moment - Photo 5",
    "category": "Photos"
  },
  {
    "type": "image",
    "src": "/gallery/992ba7f0-19e7-41e8-b98b-712a8007f620.jpg",
    "caption": "Pranil Moment - Photo 6",
    "category": "Photos"
  },
  {
    "type": "image",
    "src": "/gallery/20250201_115732.jpg",
    "caption": "Event Photo - Feb 1, 2025",
    "category": "Photos"
  },
  {
    "type": "image",
    "src": "/gallery/20250527_142854.jpg",
    "caption": "Event Photo - May 27, 2025",
    "category": "Photos"
  },
  {
    "type": "image",
    "src": "/gallery/unnamed (9).webp",
    "caption": "Unnamed (9)",
    "category": "Photos"
  },
  {
    "type": "image",
    "src": "/gallery/unnamed (10).webp",
    "caption": "Unnamed (10)",
    "category": "Photos"
  },
  {
    "type": "image",
    "src": "/gallery/unnamed (14).webp",
    "caption": "Unnamed (14)",
    "category": "Photos"
  },
  {
    "type": "image",
    "src": "/gallery/WhatsApp Image 2026-05-20 at 11.41.11 AM.jpeg",
    "caption": "Group Highlight - May 20, 2026",
    "category": "Photos"
  },
  {
    "type": "image",
    "src": "/gallery/WhatsApp Image 2026-05-20 at 11.41.16 AM.jpeg",
    "caption": "Group Highlight - May 20, 2026",
    "category": "Photos"
  },
  {
    "type": "image",
    "src": "/gallery/WhatsApp Image 2026-05-23 at 2.47.43 PM.jpeg",
    "caption": "Group Highlight - May 23, 2026",
    "category": "Photos"
  },
  {
    "type": "video",
    "src": "https://www.youtube.com/watch?v=DvtPPcwS0Mw",
    "caption": "Pranil Event Highlight - Video 1",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "https://www.youtube.com/watch?v=Gi1t7V10kb8",
    "caption": "Pranil Event Highlight - Video 2",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "https://www.youtube.com/shorts/7qt2USL-J8Y",
    "caption": "Pranil Event Highlight - Video 3",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "https://www.youtube.com/shorts/hV9An8wEb7s",
    "caption": "Pranil Event Highlight - Video 4",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "https://www.youtube.com/shorts/E7e2DouAQUs",
    "caption": "Pranil Event Highlight - Video 5",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "https://www.youtube.com/shorts/A93CQGijjRw",
    "caption": "Pranil Event Highlight - Video 6",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "https://www.youtube.com/shorts/aWJBRbWh7ec",
    "caption": "Pranil Event Highlight - Video 7",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "https://www.youtube.com/shorts/d_xDnK902Pg",
    "caption": "Pranil Event Highlight - Video 8",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "https://www.youtube.com/shorts/vAmsq8RxqNI",
    "caption": "Pranil Event Highlight - Video 9",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "https://www.youtube.com/shorts/02uk4ciSAjc",
    "caption": "Pranil Event Highlight - Video 10",
    "category": "Videos"
  }
];
